/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {

    private static final String DB_URL = "jdbc:mysql://localhost:3306/draft_picker";
    private static final String USER = "draft_picker";
    private static final String PASS = "yutapo0302";

    public static void main(String[] args) {
        Connection conn = null;

        try {
            // JDBCドライバをロード
            Class.forName("com.mysql.cj.jdbc.Driver");

            // データベースに接続
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connection established successfully!");

            // TODO: データベース操作をここに追加

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
}
